# sim_tab ----
sim_tab <- tabItem(
  tabName = "sim_tab",
  fluidRow(
    column(width = 6,
        box(width = NULL,
            title = "Generate the model",
            status = "primary",
            solidHeader = TRUE,
            numericInput(inputId = "simulations",
                         label = "Simulations",
                         value = 1000,
                         min = 1,
                         step = 50),
            numericInput(inputId = "corr",
                         label = "Correlation",
                         value = 0.5,
                         min = -1,
                         max = 1,
                         step = 0.1),
            numericInput(inputId = "sample_size",
                         label = "Sample size",
                         value = 200,
                         min = 1,
                         step = 10),
            numericInput(inputId = "intercept",
                         label = "Intercept",
                         value = 1),
            # numericInput(inputId = "coefs",
            #              label = "True coefficient value",
            #              value = 1),
            numericInput(inputId = "snr",
                         label = "Signal to Noise Ratio",
                         min = 0,
                         value = 0.5,
                         step = .1),
            selectInput(inputId = "fit_crit",
                        label = "Fit criterion",
                        choices = c("AIC", "BIC")
            ),
            actionButton("simulate", "Simulate"))),
    column(width = 6,
            box(width = NULL,
                title = "",
                solidHeader = TRUE,
                status = "primary",
                collapsible = TRUE,
                numericInput(inputId = "n_pred",
                             label = "Number of predictors",
                             value = 1,
                             min = 1),
                uiOutput("preds")
            ))
    ),
  fluidRow(
    column(width = 6,
      box(width = NULL,
          title = "Results",
          solidHeader = TRUE,
          status = "primary",
          uiOutput("rsq_output"),
          reactableOutput("res_table"))),
    column(width = 6,
      box(width = NULL,
          title = "Sampling distribution",
          solidHeader = TRUE,
          status = "primary",
          radioGroupButtons(inputId = "estimate_plot",
                      #label = "Sampling distribution of",
                      choices = c("Parameter estimates", "t-values"),
                      justified = TRUE),
          selectInput(inputId = "pred_plot",
                      label = "For regressor",
                      choices = NULL,
          ),
          plotOutput("sim_plot")))
  )
)