# sim_tab ----
sim_tab <- tabItem(
  tabName = "sim_tab",
  fluidRow(
    column(width = 6,
    box(#title = "Parameters setting",
        width = NULL,
        solidHeader = TRUE,
        numericInput(inputId = "simulations",
                    label = "Simulations",
                    value = 1000,
                    min = 1),
        numericInput(inputId = "corr",
                     label = "Correlation",
                     value = 0.5,
                     min = -1,
                     max = 1,
                     step = 0.1),
        numericInput(inputId = "sample_size",
                     label = "Sample size",
                     value = 200,
                     min = 1,
                     step = 10),
        numericInput(inputId = "intercept",
                     label = "Intercept",
                     value = 1),
        # numericInput(inputId = "coefs",
        #              label = "True coefficient value",
        #              value = 1),
        numericInput(inputId = "snr",
                     label = "Signal to Noise Ratio",
                     value = 0.5,
                     step = .1),
        selectInput(inputId = "fit_crit",
                    label = "Fit criterion",
                    choices = c("AIC", "BIC"),
                    ),
        actionButton("simulate", "Simulate")
        
  )),
  column(width = 6,
         box(width = NULL,
             collapsible = TRUE,
           numericInput(inputId = "n_pred",
                        label = "Number of predictors",
                        value = 1,
                        min = 1),
           uiOutput("preds")
         ))),
  fluidRow(
    column(width = 6,
      box(width = NULL,
          reactableOutput("res_table"))),
    column(width = 6,
      box(width = NULL,
          selectInput(inputId = "pred_plot",
                      label = "Sampling distribution of regression coefficient t-values for regressor",
                      choices = NULL,
          ),
          plotOutput("sim_plot")))
  )
)