# sim_tab ----
sim_tab <- tabItem(
  tabName = "sim_tab",
  
    box(title = "Parameters setting",
        solidHeader = TRUE,
        numericInput(inputId = "simulations",
                    label = "Simulations",
                    value = 1000,
                    min = 1),
        numericInput(inputId = "corr",
                     label = "Correlation",
                     value = 0.5,
                     min = -1,
                     max = 1,
                     step = 0.1),
        numericInput(inputId = "sample_size",
                     label = "Sample size",
                     value = 250,
                     min = 1,
                     step = 10),
        numericInput(inputId = "intercept",
                     label = "Intercept",
                     value = 1),
        numericInput(inputId = "n_param",
                     label = "Number of parameters",
                     value = 1,
                     min = 1),
        numericInput(inputId = "coefs",
                     label = "True coefficient value",
                     value = 0),
        numericInput(inputId = "snr",
                     label = "Signal to Noise Ratio",
                     value = 0.5,
                     step = .1),
        actionButton("simulate", "Simulate")
        
  ),
  tableOutput("res_table"),
  plotOutput("sim_plot")
)